# Conda environment file for the pipeline dependencies
name: nanopore-rna-mod
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - nextflow=23.04.0
  - samtools=1.17
  - minimap2=2.24
  - biopython=1.81
  - numpy=1.24.0
  - pandas=2.0.0
  - pip
  - pip:
    - ont-fast5-api
    - pod5